---
title: "changingR0"
author: "The Infective Collective (Aurora)"
output: html_document
---

```{r setup, include=FALSE}
library(Rcpp)
library(tidyverse)
library(reshape2)
source("params.R")
sourceCpp("SIRmodel_npatch.cpp")
set.seed(20)

# set plotting theme for ggplot
theme_set(theme_bw())
```

#
```{r functions}
coherence_calc <- function(x) {
  norm(x - rep(mean(x), length(x)), type = "2")
}

run_SIR <- function(p, init, m, seas) {
  # get number of patches
  n <- nrow(m)
  
  # Run the model
  raw.result <- SIRmodel_npatch(p, init, m, seas)
  
  # Initialize result data frame
  result <- data_frame(t = raw.result$time)
  
  # Pull results
  S <- raw.result$S
  I <- raw.result$I
  R <- raw.result$R
  
  # Change column names
  colnames(S) <- str_c("S", 1:n)
  colnames(I) <- str_c("I", 1:n)
  colnames(R) <- str_c("R", 1:n)
  
  # Combine data frames 
  cbind(result, S, I, R) 
}

# Generate initial conditions
r.init <- function(m) { 
  initial <- list(
      S = round(rep(base.init$S, m) + runif(m, -base.init$S, base.init$S)),
      I = round(rep(base.init$I, m) + runif(m, - base.init$I, 30*base.init$I))
  )
  initial$R <- rep(base.params$pop, m) - initial$S - initial$I
  initial
}

initial3 <- list(
    S=c(0.05, 0.07) * 1e6,
    I=c(0.0001, 0.0001) * 1e6,
    R=(1-0.0001-c(0.05, 0.07)) * 1e6
)

```

```{r initialinvestigation}
## If you want to use a different parameter. below we plot time versus incidence with different R_0 values
mpatches <- 2 #2 gives no coherence and 17 gives coherence
pp <- base.params

pp[["R0"]] <- 17
pp[["nsteps"]]<-365*100
```

```{r Coherencestuff}
new.M <- matrix(c(0.999, 0.001, 0.001, 0.999), 2, 2)
Icols <- str_c("I", 1:mpatches)
df3 <- run_SIR(pp, initial3, new.M, seasonal_cosine)
coherence <- apply(df3[,Icols], 1, coherence_calc)
# melt data frame for easy plotting
plot.df <- melt(df3, c("t"), Icols, variable.name = "compartment", value.name = "prevalence")

# plot result
ggplot(plot.df) +
  geom_line(aes(t, prevalence, colour = compartment)) +
  geom_line(data = result, aes(t, coherence), size = 1, alpha = 0.35) #+
  #scale_y_log10()
```

```{r multipleruns}
runs <- 10

# Initialize with a first run
result <- run_SIR(pp, initial3, new.M, seasonal_cosine)

# calculuate coherence for the first run
coherence <- apply(result[,Icols], 1, coherence_calc)

# initialize a data frame holding the coherence vector for the first run
coherence.df <- result %>%
  select(t) %>%
  cbind(tibble("1" = coherence))

for (i in as.character(2:runs)) {
  # run model
  result <- run_SIR(pp, initial3, new.M, seasonal_cosine)

  # calculate coherence
  coherence <- apply(result[,Icols], 1, coherence_calc)
  
  # add to the data frame of coherences
  coherence.df[, i ] <-  coherence
  
}
plot.df <- melt(coherence.df, c("t"), as.character(1:runs), variable.name = "run", value.name = "coherence")

# print settings
print(M, digits = 1)
print(result[1, ])

# plot result
ggplot(plot.df) +
  geom_line(aes(t, coherence, colour = run)) +
  scale_y_log10() +
  theme(legend.position = "none")
```
