---
title: "Investigating mixing structure"
author: "The Infective Collective (Michael Chong)"
date:
output:
  html_document:
    toc: true
    code_folding: hide
---

## Setup 
### Load packages
```{r setup} 
library(Rcpp)
library(tidyverse)
library(reshape2)
source("params.R")
sourceCpp("SIRmodel_npatch.cpp")
set.seed(20)

# set plotting theme for ggplot
theme_set(theme_bw())
```

### Convenience functions
```{r convenience-functions}
# function to run model and return data frame
run_SIR <- function(p, init, m, seas) {
  # get number of patches
  n <- nrow(m)
  
  # Run the model
  raw.result <- SIRmodel_npatch(p, init, m, seas)
  
  # Initialize result data frame
  result <- data_frame(t = raw.result$time)
  
  # Pull results
  S <- raw.result$S
  I <- raw.result$I
  R <- raw.result$R
  
  # Change column names
  colnames(S) <- str_c("S", 1:n)
  colnames(I) <- str_c("I", 1:n)
  colnames(R) <- str_c("R", 1:n)
  
  # Combine data frames 
  cbind(result, S, I, R) 
}

# coherence metric calculation
coherence_calc <- function(x) {
  norm(x - rep(mean(x), length(x)), type = "2")
}

# Generate initial conditions
r.init <- function(m) { 
  initial <- list(
      S = round(rep(base.init$S, m) + runif(m, -base.init$S, base.init$S)),
      I = round(rep(base.init$I, m) + runif(m, - base.init$I, 30*base.init$I))
  )
  initial$R <- rep(base.params$pop, m) - initial$S - initial$I
  initial
}
```

## Test run
```{r test-run}
# Dispersal matrix
mpatches <- 3
M <- matrix(rep(mpatches^(-1), mpatches^2), mpatches, mpatches)

# character vector containing "I#" column names
Icols <- str_c("I", 1:mpatches)

# run model
result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

# calculate coherence
coherence <- apply(result[,Icols], 1, coherence_calc)

# melt data frame for easy plotting
plot.df <- melt(result, c("t"), Icols, variable.name = "compartment", value.name = "prevalence")

# plot result
ggplot(plot.df) +
  geom_line(aes(t, prevalence, colour = compartment)) +
  geom_line(data = result, aes(t, coherence), size = 1.5, alpha = 0.35)
```

## Nearest Neighbour Coupling
Note that there is only a distinction between nearest-neighbour coupling and equal coupling when there are more than 3 patches.
```{r nn-settings}
mpatches <- 4
p <- 0.6 #proportion that stay in their own 
M <- matrix(c(p, (1-p)/2, 0, (1-p)/2,
              (1-p)/2, p, (1-p)/2, 0,
              0, (1-p)/2, p, (1-p)/2, 
              (1-p)/2, 0, (1-p)/2, p), 
            nrow = mpatches, ncol = mpatches)

# character vector containing "I#" column names
Icols <- str_c("I", 1:mpatches)

result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

# calculate coherence
coherence <- apply(result[,Icols], 1, coherence_calc)

# melt data frame for easy plotting
plot.df <- melt(result, c("t"), Icols, variable.name = "compartment", value.name = "prevalence")

# print settings
print(M, digits = 1)
print(result[1, ])

# plot result
ggplot(plot.df) +
  geom_line(aes(t, prevalence, colour = compartment)) +
  geom_line(data = result, aes(t, coherence), size = 1.5, alpha = 0.35) +
  scale_y_log10()
```

### Multiple runs
```{r nn-multiple}
mpatches <- 4
p <- 0.99 # proportion that only interact within their own
M <- matrix(c(p, (1-p)/2, 0, (1-p)/2,
              (1-p)/2, p, (1-p)/2, 0,
              0, (1-p)/2, p, (1-p)/2, 
              (1-p)/2, 0, (1-p)/2, p), 
            nrow = mpatches, ncol = mpatches)
Icols <- str_c("I", 1:mpatches)
runs <- 10

# Initialize with a first run
result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

# calculuate coherence for the first run
coherence <- apply(result[,Icols], 1, coherence_calc)

# initialize a data frame holding the coherence vector for the first run
coherence.df <- result %>%
  select(t) %>%
  cbind(tibble("1" = coherence))

for (i in as.character(2:runs)) {
  # run model
  result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

  # calculate coherence
  coherence <- apply(result[,Icols], 1, coherence_calc)
  
  # add to the data frame of coherences
  coherence.df[, i ] <-  coherence
  
}
plot.df <- melt(coherence.df, c("t"), as.character(1:runs), variable.name = "run", value.name = "coherence")

# print settings
print(M, digits = 1)
print(result[1, ])

# plot result
ggplot(plot.df) +
  geom_line(aes(t, coherence, colour = run)) +
  scale_y_log10() +
  theme(legend.position = "none")
```


## Equal coupling
```{r eq-settings}
mpatches <- 4
p <- 0.99 # proportion that only interact within their own
M <- matrix((1-p)/(mpatches-1), nrow = mpatches, ncol = mpatches)
diag(M) <- p

# character vector containing "I#" column names
Icols <- str_c("I", 1:mpatches)

# run model
result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

# calculate coherence
coherence <- apply(result[,Icols], 1, coherence_calc)

# melt data frame for easy plotting
plot.df <- melt(result, c("t"), Icols, variable.name = "compartment", value.name = "prevalence")

# print settings
print(M, digits = 1)
print(result[1, ])

# plot result
ggplot(plot.df) +
  geom_line(aes(t, prevalence, colour = compartment)) +
  geom_line(data = result, aes(t, coherence), size = 1.5, alpha = 0.35) +
  scale_y_log10()
```

### Multiple runs
```{r eq-multiple}
mpatches <- 4
p <- 0.99 # proportion that only interact within their own
M <- matrix((1-p)/(mpatches-1), nrow = mpatches, ncol = mpatches)
diag(M) <- p
Icols <- str_c("I", 1:mpatches)
runs <- 10

# Initialize with a first run
result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

# calculuate coherence for the first run
coherence <- apply(result[,Icols], 1, coherence_calc)

# initialize a data frame holding the coherence vector for the first run
coherence.df <- result %>%
  select(t) %>%
  cbind(tibble("1" = coherence))

for (i in as.character(2:runs)) {
  # run model
  result <- run_SIR(base.params, r.init(mpatches), M, seasonal_cosine)

  # calculate coherence
  coherence <- apply(result[,Icols], 1, coherence_calc)
  
  # add to the data frame of coherences
  coherence.df[, i ] <-  coherence
  
}
plot.df <- melt(coherence.df, c("t"), as.character(1:runs), variable.name = "run", value.name = "coherence")

# print settings
print(M, digits = 1)
print(result[1, ])

# plot result
ggplot(plot.df) +
  geom_line(aes(t, coherence, colour = run)) +
  scale_y_log10() +
  theme(legend.position = "none")
```

